### ISSUE TITLE
Non-string merge vars

### ISSUE THREAD

**Issue by buttash** [banana-j/bananaj#31]
At the moment line 123 of Mailchimp.java and line 63 of Member.java.assume all merge vars are strings.  This causes an issue as I am migrating from another Java wrapper where I have been able to set integer merge vars.

Might it be possible to change these lines to:

`String value = memberMergeTags.get(key).toString();`

Also, line 55 fails as I have no "interests" set.  Maybe a change to:

`    	final JSONObject interests = (member.has("interests")) ? member.getJSONObject("interests") : null;`

might help?

Thanks
Martin

**Comment by alexanderwe** [comment]
Hi @buttash, you are completely right. It would be better to cast the merge tags and also account for null objects. I will try to solve these issues in the upcoming weekend

**Comment by gscriver** [comment]
Merge fields are now of type Object. A unit test was added for a merge field with JSON Object type.
