### ISSUE TITLE
Is this JDK still supported?

### ISSUE THREAD

**Issue by yekbote-pavan** [banana-j/bananaj#46]
I am planning to use this JDK for writing a connector for Mailchimp. I was wondering if this is still supported?

**Comment by yekbote-pavan** [comment]
Does it support OAuth based API calls?

**Comment by gscriver** [comment]
A contributor added usingOAuthToken(...) and withDc(...) to the MailChimpConnection Builder class for OAuth support. I have not personally tested OAuth integration so I cannot speak to how well it works.
