### ISSUE TITLE
Does "all" pagination actually work?

### ISSUE THREAD

**Issue by chris13524** [banana-j/bananaj#48]
For functions that accept pagination (e.g. [`getMembers(count, offset)`](https://github.com/banana-j/bananaj/blob/master/src/main/java/com/github/alexanderwe/bananaj/model/list/MailChimpList.java#L118)), passing a value of 0 is supposed to return *all* the items from Mailchimp. These functions are implemented by simply passing the total number as the `count` parameter. However, the API docs [indicate](https://mailchimp.com/developer/reference/lists/list-members/#get_/lists/-list_id-/members) that the maximum value that can be passed here is 1000.

Now I haven't tested this as we aren't big enough, but looking a the code it seems that the functionality might break after 1000 items.

Would these functions need to be re-implemented to hit the endpoints multiple times to get the full list?

**Comment by gscriver** [comment]
This is actually an issue with most entity types, not just members. This has been partially addressed in the development branch. A 0 count is no longer allowed and offset must be in the range of 1-1000.

You can iterate over all members with the following code:

`int offset=0;`
`List<Member> membersOfList = myList.getMembers(1000,offset);`
`  while (membersOfList.size() > 0) {`
`    for(Member member : membersOfList) {`
`      // do something`
`    }`
`    membersOfList = myList.getMembers(1000,offset+=1000);`
`  }`

We have been debating a few possibilities. Should we provide a method, myList.getMembers(), with no parameters that will internally perform the iteration and return a list of all members. Internally handle offsets greater than 1000 in the library, or only provide a paginated version of the method honoring Mailchimp's API limits. 
We have been moving towards the last option, as demonstrated in the sample code above. We would like to hear your opinion and reasons before we commit to a specific pattern and migrate the entire library.

**Comment by chris13524** [comment]
I'd 100% prefer returning an `Iterable`/`Iterator` over exposing `(offset, count)`. I can't think of any situation where you'd actually need access to offset and count, can you? You'd generally want to iterate over the whole list of something. Unless it was sorted server-side and you just wanted the first item?

If we still want to expose `(offset, count)` (maybe we come up with a use-case), then I see no reason we couldn't overload the function to accept no args or both args? Shouldn't add a significant amount to the actual implementation. However maybe best if that goes in a separate `getMembersPages()` function if we want to pass query params to the function.

**Comment by gscriver** [comment]
Offset and count is defiantly used in web interfaces for pagination. 

My initial thoughts are to add a layer to the library that handles iterables. Perhaps a generic. That is to say the low level API should be a simple wrapper around the REST API. An additional layer could then be used to wrap iterators around the low level API. The iterator implementation could use a background look ahead thread to pre-load the next page while the current page is being iterated.

**Comment by chris13524** [comment]
Do people build web interfaces to manage Mailchimp contacts (rather than using Mailchimp's own interface?) Kinda weird use-case, but I'm not judging.

It would be nice to find some sort of abstraction for the iteration to avoid lots of redundant boilerplate for every paginated endpoint.

**Comment by gscriver** [comment]
Agreed, minimize boilerplate. That is why I was thinking of generics to do most of the heavy lifting.

The web interfaces I know of are used mostly for custom reporting, self registration, categories and tags.

**Comment by gscriver** [comment]
Version 0.7.0 replaced pagination APIs with iterators.
