### ISSUE TITLE
Change request for Mailchimplist getMember function

### ISSUE THREAD

**Issue by joranb** [banana-j/bananaj#53]
I think it would be more practical if this wrapper created a MD5 hash of the email and converted it to lower case, so the method signature of getMember would be getMember(String email) and not getMember(subscriberHash). I would believe that most of the users of this wrapper store their emails as emails, and not as MD5 hashes of email (but then again, I am no expert).

**Comment by SavvasGaryScriver** [comment]
The MailChimpList methods now accept either the member's email address or subscriber hash.

**Comment by gscriver** [comment]
As of version 0.7.0 all APIs that expect an email address accept either the MD5 hash or email address

**Comment by joranb** [comment]
@gscriver 
I can't see that version in releases, but found it on Maven Central. Using that version however gives: java: package com.github.alexanderwe.bananaj.connection does not exist

Have to roll back to previous.

**Comment by SavvasGaryScriver** [comment]
The official releases can be found at https://mvnrepository.com/artifact/com.github.banana-j/bananaj

**Comment by joranb** [comment]
I just did not catch that you changed the package name, this part had to be removed: alexanderwe
